out_dir: results
metric_best: auc
run_multiple_splits: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
wandb:
  use: False
  project: Minesweeper
dataset:
  format: hete_new
  name: Minesweeper
  task: node
  task_type: classification
  transductive: True
  split_mode: standard
  node_encoder: True
  node_encoder_name: LinearNode
#  node_encoder_name: LinearNode+GraphormerBias
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: DummyEdge
  edge_encoder_bn: False
train:
  mode: custom
  sampler: full_batch
#  sampler: saint_rw
#  batch_size: 32
  eval_period: 1
  enable_ckpt: False
#  ckpt_period: 100
model:
  type: WaveModel
  loss_fun: cross_entropy
  edge_decoding: dot
gt:
  layer_type: GCN+WaveGC
  layers: 5
  n_heads: 8
  dim_hidden: 512  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.2
  attn_dropout: 0.0
  layer_norm: True
  batch_norm: False
gnn:
  head: node
  layers_pre_mp: 1
  layers_post_mp: 1
  dim_inner: 512  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: gelu
  dropout: 0.2
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adam
  weight_decay: 1e-5
  base_lr: 5e-4
  max_epoch: 500
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
WaveGC:
  nheads: 2
  trans_dropout: 0.1
  adj_dropout: 0.0
  drop: 0.8
  num_J: 2
  num_n: 8
  pre_s: [0.5, 0.8]
  tight_frames: True
  weight_share: True
  trans_use: False
  keep_eig_ratio: 0.5
  keep_thre: 0.1