out_dir: results
metric_best: accuracy
wandb:
  use: True
  project: Actor
dataset:
  format: PyG-Actor
  name: none
  task: node
  task_type: classification
  transductive: True
  split_mode: standard
  node_encoder: True
  node_encoder_name: LapPE
#  node_encoder_name: LinearNode+GraphormerBias
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: DummyEdge
  edge_encoder_bn: False
posenc_LapPE:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 4
  model: DeepSet
  dim_pe: 4
  layers: 2
  n_heads: 4  # Only used when `posenc.model: Transformer`
  raw_norm_type: none
train:
  mode: custom
  sampler: full_batch
#  sampler: saint_rw
#  batch_size: 32
  eval_period: 5
  enable_ckpt: False
#  ckpt_period: 100
model:
  type: WaveSAN
  loss_fun: cross_entropy
  edge_decoding: dot
gt:
  layers: 2
  n_heads: 4
  dim_hidden: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  full_graph: False
  gamma: 1e-5
  dropout: 0.2
  attn_dropout: 0.0
  layer_norm: False
  batch_norm: True
  residual: True
  layer_type: genwave
gnn:
  head: node
  layers_pre_mp: 0
  layers_post_mp: 1
  dim_inner: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: gelu
  dropout: 0.2
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.0005
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
WaveGC:
  nheads: 8
  trans_dropout: 0.1
  adj_dropout: 0.0
  drop: 0.5
  num_n: 5
  num_J: 3 
  pre_s: [0.1, 0.5, 1.0]
  tight_frames: True
  weight_share: False
  trans_use: False
  keep_eig_ratio: 1.0
  keep_thre: 1e-2